services:
  browser-node:
    image: seadfeng/playwright-browser-worker
    env_file: .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 1GB
  app:
    image: seadfeng/playwright-browser-app
    env_file: .env 
    restart: unless-stopped